---
abstract: 'Take old or new Word files and spit out HTML5'
author:
  - 'Amiri Barksdale <amiri@arisdottle.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MSWord-ToHTML5
no_index:
  directory:
    - inc
    - t
requires:
  Archive::Zip: 0
  Archive::Zip::MemberRead: 0
  Carp: 0
  Devel::Dwarn: 0
  File::Basename: 0
  File::Path: 0
  File::Spec: 0
  IO::All: 0
  IO::All::File: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Method::Signatures: 0
  MooseX::Types: 0
  MooseX::Types::IO::All: 0
  MooseX::Types::Moose: 0
  Path::Class::Dir: 0
  Test::Most: 0
  Text::Extract::Word: 0
  XML::LibXML: 0
  XML::LibXSLT: 0
  autodie: 0
  namespace::autoclean: 0
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/amiri/MSWord-ToHTML5.git
version: 0.001
